services:
  api:
    build:
      target: dev
    image: g-dash-api-dev
    environment:
      NODE_ENV: development
      LOG_FORMAT: dev
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
    volumes:
      - ./apps/api:/repo/apps/api
      - /repo/apps/api/node_modules

  web:
    build:
      target: dev
    image: g-dash-web-dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:${API_PORT:-4100}/api/v1
      NEXT_PUBLIC_SITE_URL: http://localhost:${WEB_PORT:-3000}
      API_INTERNAL_URL: http://api:4100/api/v1
      WATCHPACK_POLLING: "true"
    volumes:
      - ./apps/web:/repo/apps/web
      - /repo/apps/web/node_modules
      - /repo/apps/web/.next
    depends_on:
      api:
        condition: service_started
